#!/usr/bin/python3

# ---------------------------------
# Purpose: Individual Functions

# Version: 1
#
# Projector Model: TSW-760
#
# November 25, 2019
# ----------------------------------

import requests
import urllib3

urllib3.disable_warnings()


def Reboot(host):
    print("Trying to Reboot")
    Data = {"Device": {"DeviceOperations": {"Reboot": "true"}}}
    reboot = requests.post(url="http://" + host + "/Device/DeviceOperations", json=Data, verify=False)

    print(reboot.status_code)
    print(reboot.text)


def Restore(host):
    print("Trying to Restore")
    Data = {"Device": {"DeviceOperations": {"Restore": "true"}}}

    restore = requests.post(url="http://" + host + "/Device/DeviceOperations", json=Data, verify=False)
    print(restore.status_code)
    print(restore.text)
